### ISSUE TITLE
make lib-dependencies create CRAN and library with the wrong owner

### ISSUE THREAD

**Issue by programLyrique** [PRL-PRG/evalr-experiment#1]
`make lib-dependencies` create directories  _CRAN_ and _library_ with the wrong owner and group: root instead of the non-privileged owner.  The non-privileged owner is in the _docker_ group.

On Debian Unstable.

```bash 
docker --version
Docker version 20.10.6, build 370c289
```

I manually corrected the owner and group and the next runs of `make lib-dependencies` did not change them back to root.

**Comment by fikovnik** [comment]
fixed in: 70f312d6fde7ce15aa4e5952b90e4afffce34aba
