### ISSUE TITLE
Remove git support in the docker image

### ISSUE THREAD

**Issue by programLyrique** [PRL-PRG/evalr-experiment#4]
git support inside the docker image, for instance when doing `make evil` is fragile. 
It needs to have the ssh agent to be well configured, which can be tedious when using tmux. 

I suggest that if we need to update some of the libraries, we do it in another shell out of the docker image.

**Comment by fikovnik** [comment]
fixed in: fd4c7015789876f8d87207b3adce5f2d09560e16
